---
- name: Converge
  hosts: all
  vars:
    pyenv_python_versions:
      - version: 3.7.7
      - version: 2.7.8
        state: absent
      - version: 3.8.3
        global: "yes"
    pyenv_dir: ~/.pyenv
  roles:
    - agoloncser.pyenv
